name: 'train'
device: 'cuda:0'
seed: 42
output_dir: ./work_dirs
num_workers: 4
resume: null  # 如果存在，则恢复训练

data:
  data_root: ./dataset/OdinMJ
  data_format: 'default'  # [default, custom]
  label_format: 'coco'  # [yolo, coco]
  labels: [People"]  # 类别列表, 默认从0开始
  transforms:
    random_flip: 0.0
    random_rotation: 0.0
    random_resize: 0.0
    color_jitter: 0.0
    gamma_correction: 0.0
    random_erase: 0.0
    blur_sigma: 0.0

model:
  num_classes: 1
  backbone_name: "hgnetv2"  # ['swint', 'resnet50', 'hgnetv2']
  pretrained: True  # 是否使用BackBone预训练权重
  img_size: [512, 640]
  out_dims: [256, 512, 1024]
  roi_sizes: [14, 7, 3]

criterion:
  weight_dict:
    loss_vfl:  1.0
    loss_bbox: 5
    loss_giou: 2
    loss_fgl: 0.15
    loss_ddf: 1.5
  losses: ['vfl', 'boxes', 'focal']
  alpha: 0.75
  gamma: 2.0
  reg_max: 32
  matcher:
    weight_dict:
      cost_class: 2
      cost_bbox: 5
      cost_giou: 2
    alpha: 0.25
    gamma: 2.0

logger:
  log_name: 'Seg_log'
  level: 'INFO'

training:
  start_epoch: 1
  epochs: 200
  scheduler: 'step'  # [step, plateau]
  lr: 0.0001
  lr_backbone: 0.00001
  lr_drop: 200
  batch_size: 8
  eval_freq: 1
  start_eval: 1
  threshold: 0.5
  step_size: 30
  log_interval: 10
  gamma: 0.1

test:
  img_dirs: './data'
  batch_size: 1
  threshold: 0.5
  device: 'cuda:1'
  save_dir: "./work_dirs"
  name: "test"
  weight_path: "./work_dirs/train_3/checkpoints/best_iou.pth"
  show: True
  show_overlay: False