name: 'train'
device: 'cuda:1'
seed: 42
output_dir: ./work_dirs
num_workers: 8
resume: null  # 如果存在，则恢复训练

data:
  data_root: './dataset/OdinMJ_'
  data_format: 'default'  # [default, custom]
  label_format: 'yolo'  # [yolo, coco]
  labels: ["People"]  # 类别列表, 默认从0开始
  transforms:
    random_flip: 0.0            # 水平/垂直翻转概率
    random_rotation: 0.0        # 最大旋转角度 ±10°
    random_resize: 0.0          # 缩放比例范围 ±20%
    color_jitter: 0.0           # 颜色扰动强度 (brightness, contrast, saturation)
    gamma_correction: 0.0       # Gamma 校正概率
    random_erase: 0.0           # 随机擦除概率
    blur_sigma: 0.0             # 高斯模糊（暂时关闭）

model:
  num_classes: 1
  backbone_name: "hgnetv2"  # ['swint', 'resnet50', 'hgnetv2']
  pretrained: True  # 是否使用BackBone预训练权重
  img_size: [512, 640]
  out_dims: [512, 1024, 2048]
  aagf:
    roi_sizes: [14, 7, 3]
    use_confidence: True # 置信度融合
    use_attention: False  # 相似度融合
    use_similarity: False  # 注意力融合

criterion:
  weight_dict:
    loss_vfl:  1.0
    loss_bbox: 5
    loss_giou: 2
    loss_fgl: 0.15
    loss_ddf: 1.5
  losses: ['vfl', 'boxes', 'focal']
  alpha: 0.75
  gamma: 2.0
  reg_max: 32
  matcher:
    weight_dict:
      cost_class: 2
      cost_bbox: 5
      cost_giou: 2
    alpha: 0.25
    gamma: 2.0

logger:
  log_name: 'Seg_log'
  level: 'INFO'

training:
  start_epoch: 1
  epochs: 200
  optimizer: 'adamw' # [sgd, adam, adamw]
  betas: [0.9, 0.999]
  eps: 0.00000001
  weight_decay: 0.0001
  scheduler: 'step'  # [step, plateau, multistep, cosine, onecycle, lambda]
  lr: 0.0001
  lr_drop: 50
  gamma: 0.1
  lr_backbone: 0.00001
  batch_size: 8
  start_eval: 1
  eval_freq: 1
  log_interval: 0

test:
  img_dirs: './data'
  batch_size: 1
  device: 'cuda:1'
  save_dir: "./work_dirs"
  name: "test"
  weight_path: "./work_dirs/train_3/checkpoints/best_iou.pth"
  show: True
  show_overlay: False